#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated By: Claude Code (claude-opus-5)
#
# Record which model authored the changes in a repo, so scripts/commit can turn
# that into Assisted-by trailers instead of naming whoever wrote the commit
# message.
#
# Two events, one job each:
#
#   PostToolUse  append "<Tool>|<model>" to every repo this call could touch
#   Stop         drop that record for any repo whose tree is clean
#
# Recording is deliberately credulous and the Stop purge is what makes it
# honest. The alternative -- fingerprinting the tree before and after every
# call to decide whether to record -- costs a git walk per call and still gets
# the interesting case wrong: a change made and then reverted moves the
# fingerprint twice, records an author, and leaves that attribution attached to
# whatever is committed later. Recording eagerly and deleting when the tree
# comes out clean handles the revert for free.
#
# What it costs: a model that only ran a shell command in a repo that was
# already dirty is credited alongside whoever actually wrote the change. There
# is no signal available at hook time that separates those two, and over-
# attribution is the safer direction -- a missing author is a wrong commit
# message, an extra one is a visible extra line.
#
# Nothing here asks a model to report its own identity. Codex puts the model in
# the hook payload; Claude Code does not, so it is read from the transcript the
# harness itself writes.
#
# A sub-agent's work is recorded against the session's model, not the model the
# sub-agent ran on. Its calls do fire this hook -- they arrive with `agent_id`
# and `agent_type` set -- but `transcript_path` is the main session transcript,
# whose assistant entries only ever name the session model. Measured: a haiku
# sub-agent writing a file recorded `claude-opus-5`. Nothing in the payload
# carries the sub-agent's model, so this is not fixable here.

import json
import os
import re
import subprocess
import sys

RECORD_DIR = ".commit-attribution"
RECORD_FILE = "record"
# scripts/commit drops this after a successful commit. The hook fires again for
# the shell call that ran it, and without this would record whoever committed
# as an author of whatever is still uncommitted -- the exact misattribution
# this mechanism exists to remove, and the normal case when the code is written
# in one harness and committed in another. One-shot: consuming it skips exactly
# that record.
SKIP_FILE = "skip-next"

# Tool names that can change a file. Only an optimisation: it saves a `git
# rev-parse` on every Grep and Read. A harness that does not name the tool in
# its payload records unconditionally and the purge still sorts it out.
# "Agent" and "Task" are the same tool under two names: Claude Code sends
# "Agent" today, and a sub-agent's own calls arrive as Bash/Write regardless.
MUTATORS = {"Agent", "Bash", "Edit", "MultiEdit", "NotebookEdit", "Task", "Write"}

PURGE_EVENTS = {"Stop", "SessionEnd"}

# Absolute paths as they appear in a serialised tool_input. Deliberately loose:
# a false candidate costs one `git rev-parse` that returns nothing.
ABS_PATH = re.compile(r"/[^\s\"',:;()\[\]{}]+")

# Enough transcript tail to hold a recent assistant entry. The first line of
# the chunk is usually truncated mid-JSON; the reverse scan skips it.
TAIL_BYTES = 256 * 1024

LABELS = {"codex": "Codex"}
DEFAULT_LABEL = "Claude Code"


def git(cwd, *args):
    """Run git in cwd, returning stdout, or None if it failed for any reason."""
    try:
        result = subprocess.run(
            ("git", "-C", cwd) + args, capture_output=True, text=True, timeout=30
        )
    except (OSError, subprocess.SubprocessError):
        return None
    return result.stdout if result.returncode == 0 else None


def toplevel(path):
    """The work-tree root containing path, or None.

    In a worktree this is the worktree's own root, which is where the commit
    will be made.
    """
    if not os.path.isdir(path):
        return None
    out = git(path, "rev-parse", "--show-toplevel")
    return (out.strip() or None) if out else None


def repos_under(directory):
    """Work-tree roots among the immediate subdirectories of directory."""
    try:
        names = os.listdir(directory)
    except OSError:
        return set()
    found = set()
    for name in names:
        sub = toplevel(os.path.join(directory, name))
        if sub:
            found.add(sub)
    return found


def candidate_repos(payload):
    """Every repo this hook fire could concern.

    Not cwd alone: a session that touches several repos has to record into each
    one separately, attributed by which repo the file belongs to.
    """
    cwd = payload.get("cwd") or os.getcwd()
    found = set()

    top = toplevel(cwd)
    if top:
        found.add(top)
    else:
        # A sandbox session starts in a directory *of* repos, not in one.
        found |= repos_under(cwd)

    for match in ABS_PATH.findall(json.dumps(payload.get("tool_input") or {})):
        directory = match if os.path.isdir(match) else os.path.dirname(match)
        sub = toplevel(directory)
        if sub:
            found.add(sub)

    return found


def purge_repos(payload):
    """Every repo a purge has to consider.

    Wider than candidate_repos, because the two events see different things. A
    PostToolUse carries the path it touched, so recording reaches any repo a
    tool named; Stop carries only cwd, and a session that recorded into a repo
    it is no longer sitting in would leave that record for a later commit in
    that repo to pick up. Sibling repos of the cwd repo are the ones reachable
    without keeping state between the two events -- a checkout tree
    (`~/source/*`, `/sandbox/source/*`) is how they sit next to each other.

    A repo outside that tree still keeps a stale record. Purging is safe to
    widen -- purge() deletes only when the tree is clean -- so if that case
    shows up, widen here rather than tracking repos across events.
    """
    repos = candidate_repos(payload)
    top = toplevel(payload.get("cwd") or os.getcwd())
    if top:
        parent = os.path.dirname(top)
        if parent and parent != top:
            repos |= repos_under(parent)
    return repos


def transcript_model(transcript_path):
    """The last model named in a Claude Code transcript, or None."""
    if not transcript_path:
        return None
    try:
        with open(transcript_path, "rb") as handle:
            handle.seek(0, os.SEEK_END)
            handle.seek(max(0, handle.tell() - TAIL_BYTES))
            chunk = handle.read()
    except OSError:
        return None

    for line in reversed(chunk.split(b"\n")):
        try:
            entry = json.loads(line)
        except (ValueError, UnicodeDecodeError):
            continue
        if not isinstance(entry, dict) or entry.get("type") != "assistant":
            continue
        model = (entry.get("message") or {}).get("model")
        # "<synthetic>" is the harness's own error message, not a model.
        if model and model != "<synthetic>":
            return model
    return None


def authoring_model(payload):
    """The model driving this hook fire, as the harness reports it.

    Codex supplies it in the payload. Claude Code does not, so fall back to the
    transcript it writes. Recorded verbatim -- no friendly-name table, because
    such a table is wrong on every model release and nothing detects when it
    goes stale.
    """
    model = payload.get("model")
    if isinstance(model, str) and model.strip():
        return model.strip()
    return transcript_model(payload.get("transcript_path"))


def tool_label(payload):
    """The harness name for the trailer, inferred from the payload shape."""
    if payload.get("model"):
        return LABELS["codex"]
    return DEFAULT_LABEL


def record_path(repo, create):
    """Path to the repo's record file, creating a self-ignoring dir if asked.

    A `.gitignore` of `*` inside an untracked directory keeps the record
    invisible to `git status` and out of `git add -A`, with no `.gitignore`
    edit in any target repo -- and, load bearing for the purge, keeps the
    directory from showing up as a change of its own.
    """
    directory = os.path.join(repo, RECORD_DIR)
    if create:
        try:
            os.makedirs(directory, exist_ok=True)
            ignore = os.path.join(directory, ".gitignore")
            if not os.path.exists(ignore):
                with open(ignore, "w") as handle:
                    handle.write("*\n")
        except OSError:
            return None
    return os.path.join(directory, RECORD_FILE)


def record(repo, label, model):
    """Append one author line, unless it is already there."""
    path = record_path(repo, create=True)
    if path is None:
        return
    line = "%s|%s\n" % (label, model)
    try:
        if os.path.exists(path):
            with open(path) as handle:
                if line in handle.read():
                    return
        with open(path, "a") as handle:
            handle.write(line)
    except OSError:
        pass


def consume_skip(repo):
    """True when scripts/commit asked for this one record to be dropped."""
    try:
        os.remove(os.path.join(repo, RECORD_DIR, SKIP_FILE))
        return True
    except OSError:
        return False


def purge(repo):
    """Drop the record when the repo has nothing to attribute.

    `git status --porcelain` is empty only when the tree is clean: no staged
    change, no unstaged change, no untracked file. Whatever the session did to
    this repo, it left nothing behind, so any author it recorded would ride
    along on some later commit it had no part in. This is also what handles a
    change that was made and then reverted.
    """
    # The skip marker goes regardless of the tree, and before the status check
    # that might return early. It suppresses the tool call that ran
    # scripts/commit, and that call's PostToolUse always lands before this
    # event, so a marker still here is one nothing consumed: the script was run
    # outside a harness, or the marker arrived with a copy of the repo from
    # another machine -- `.commit-attribution/` is gitignored, and a sandbox
    # upload sends ignored files too. Left in place it eats the next real
    # author instead, silently and possibly sessions later.
    try:
        os.remove(os.path.join(repo, RECORD_DIR, SKIP_FILE))
    except OSError:
        pass

    status = git(repo, "status", "--porcelain")
    # None means git failed. Keeping the record is the safe direction.
    if status is None or status.strip():
        return
    try:
        os.remove(os.path.join(repo, RECORD_DIR, RECORD_FILE))
    except OSError:
        pass


def main():
    try:
        payload = json.load(sys.stdin)
    except (ValueError, OSError):
        return
    if not isinstance(payload, dict):
        return

    event = payload.get("hook_event_name") or ""

    if event in PURGE_EVENTS:
        for repo in purge_repos(payload):
            purge(repo)
        return

    repos = candidate_repos(payload)

    tool = payload.get("tool_name")
    if tool is not None and tool not in MUTATORS:
        return

    model = authoring_model(payload)
    if not model:
        return
    label = tool_label(payload)
    for repo in repos:
        if consume_skip(repo):
            continue
        record(repo, label, model)


if __name__ == "__main__":
    try:
        main()
    except Exception:
        # A hook that fails must not take the session with it. No record means
        # scripts/commit falls back to COMMIT_HARNESS, which is today's
        # behaviour and the documented degradation.
        pass
