#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated By: Claude Code (claude-opus-5)
#
# Self-check for hooks/record-attribution.py. No framework: run it directly.
#
#     python3 hooks/test_record_attribution.py
#
# Drives the hook the way a harness does -- a JSON payload on stdin -- so the
# payload shapes are part of what is under test, not an internal API.

import json
import os
import shutil
import subprocess
import sys
import tempfile

HOOK = os.path.join(os.path.dirname(os.path.abspath(__file__)), "record-attribution.py")
RECORD = os.path.join(".commit-attribution", "record")

failures = []


def check(condition, message):
    if not condition:
        failures.append(message)


class Repo:
    """A throwaway git repo, isolated from host and system gitconfig.

    A host that signs commits by ssh points at a key that need not exist here,
    and a sandbox deliberately ships no ssh-keygen, so an inherited
    commit.gpgsign fails the commits below for reasons unrelated to the test.
    """

    def __init__(self, root, name):
        self.path = os.path.join(root, name)
        os.makedirs(self.path)
        self.git("init", "-q", ".")
        self.git("config", "user.email", "selftest@example.invalid")
        self.git("config", "user.name", "selftest")

    def git(self, *args):
        env = dict(os.environ, GIT_CONFIG_GLOBAL=os.devnull, GIT_CONFIG_SYSTEM=os.devnull)
        result = subprocess.run(
            ("git", "-C", self.path) + args, capture_output=True, text=True, env=env
        )
        assert result.returncode == 0, "git %s failed: %s" % (args, result.stderr)
        return result.stdout

    def write(self, name, text):
        with open(os.path.join(self.path, name), "w") as handle:
            handle.write(text)

    def records(self):
        path = os.path.join(self.path, RECORD)
        if not os.path.exists(path):
            return []
        with open(path) as handle:
            return [line.strip() for line in handle if line.strip()]


def fire(event, cwd, tool=None, model=None, transcript=None, tool_input=None):
    """Invoke the hook exactly as a harness would."""
    payload = {"hook_event_name": event, "cwd": cwd}
    if tool is not None:
        payload["tool_name"] = tool
    if model is not None:
        payload["model"] = model
    if transcript is not None:
        payload["transcript_path"] = transcript
    if tool_input is not None:
        payload["tool_input"] = tool_input
    result = subprocess.run(
        [sys.executable, HOOK], input=json.dumps(payload), capture_output=True, text=True
    )
    assert result.returncode == 0, "hook exited %s: %s" % (result.returncode, result.stderr)


def write_transcript(path, model):
    with open(path, "a") as handle:
        handle.write(json.dumps({"type": "assistant", "message": {"model": model}}) + "\n")


def main():
    root = tempfile.mkdtemp()
    try:
        # --- Claude Code: model comes from the transcript, not the payload ---
        repo = Repo(root, "claude")
        repo.write("seed.txt", "seed\n")
        repo.git("add", "-A")
        repo.git("commit", "-qm", "seed")
        transcript = os.path.join(root, "t.jsonl")
        write_transcript(transcript, "claude-opus-5")

        fire("PostToolUse", repo.path, tool="Bash", transcript=transcript)
        check(repo.records() == ["Claude Code|claude-opus-5"], "claude: %r" % repo.records())

        # A read-only tool is skipped when the harness names it.
        write_transcript(transcript, "some-other-model")
        fire("PostToolUse", repo.path, tool="Grep", transcript=transcript)
        check(
            repo.records() == ["Claude Code|claude-opus-5"],
            "non-mutator recorded: %r" % repo.records(),
        )

        # Repeats collapse rather than growing the file per tool call.
        write_transcript(transcript, "claude-opus-5")
        for _ in range(3):
            fire("PostToolUse", repo.path, tool="Edit", transcript=transcript)
        check(repo.records() == ["Claude Code|claude-opus-5"], "dup: %r" % repo.records())

        # A second model before any commit accumulates a second line.
        write_transcript(transcript, "claude-sonnet-5")
        fire("PostToolUse", repo.path, tool="Edit", transcript=transcript)
        check(
            repo.records() == ["Claude Code|claude-opus-5", "Claude Code|claude-sonnet-5"],
            "second model: %r" % repo.records(),
        )

        # --- Stop purges when the tree is clean ---
        # Nothing was actually written above, so this repo is clean.
        fire("Stop", repo.path)
        check(repo.records() == [], "clean tree kept a record: %r" % repo.records())

        # --- Stop keeps the record when there is something to attribute ---
        repo.write("work.txt", "real change\n")
        write_transcript(transcript, "claude-opus-5")
        fire("PostToolUse", repo.path, tool="Bash", transcript=transcript)
        fire("Stop", repo.path)
        check(repo.records() == ["Claude Code|claude-opus-5"], "dirty: %r" % repo.records())

        # --- the case eager recording exists for: change, then revert ---
        os.remove(os.path.join(repo.path, "work.txt"))
        fire("PostToolUse", repo.path, tool="Bash", transcript=transcript)
        fire("Stop", repo.path)
        check(repo.records() == [], "reverted change kept attribution: %r" % repo.records())

        # --- Codex: model arrives in the payload, no transcript ---
        codex = Repo(root, "codex")
        codex.write("seed.txt", "seed\n")
        codex.git("add", "-A")
        codex.git("commit", "-qm", "seed")
        codex.write("change.txt", "codex wrote this\n")
        fire("PostToolUse", codex.path, model="gpt-5-codex")
        check(codex.records() == ["Codex|gpt-5-codex"], "codex: %r" % codex.records())
        fire("Stop", codex.path)
        check(codex.records() == ["Codex|gpt-5-codex"], "codex purged early: %r" % codex.records())

        # --- multi-repo: a sibling that was not touched records nothing ---
        alpha = Repo(root, "alpha")
        beta = Repo(root, "beta")
        for each in (alpha, beta):
            each.write("seed.txt", "seed\n")
            each.git("add", "-A")
            each.git("commit", "-qm", "seed")
        beta.write("only-beta.txt", "changed\n")
        write_transcript(transcript, "claude-opus-5")
        # cwd is the directory *of* repos, as in a sandbox.
        fire("PostToolUse", root, tool="Bash", transcript=transcript)
        fire("Stop", root)
        check(beta.records() == ["Claude Code|claude-opus-5"], "beta: %r" % beta.records())
        check(alpha.records() == [], "untouched repo recorded: %r" % alpha.records())

        # --- the record is invisible to git and cannot be staged ---
        check(RECORD.split(os.sep)[0] not in beta.git("status", "--porcelain", "-uall"),
              "record is visible to git status")
        beta.git("add", "-A")
        check(RECORD.split(os.sep)[0] not in beta.git("diff", "--cached", "--name-only"),
              "record was staged")

        # --- the commit itself is not an author ---
        # The real workflow: authored in Claude, committed on the host with
        # Codex. Without the skip marker the Codex shell call that ran
        # scripts/commit is recorded against whatever is left uncommitted,
        # which is the misattribution the whole mechanism exists to remove.
        split = Repo(root, "split")
        split.write("seed.txt", "seed\n")
        split.git("add", "-A")
        split.git("commit", "-qm", "seed")
        split.write("authored.txt", "written by claude\n")
        split.write("later.txt", "also claude, not staged\n")
        write_transcript(transcript, "claude-opus-5")
        fire("PostToolUse", split.path, tool="Edit", transcript=transcript)
        check(
            split.records() == ["Claude Code|claude-opus-5"],
            "author not recorded: %r" % split.records(),
        )

        # scripts/commit: consume the record, commit part of the tree, and
        # leave the marker behind.
        split.git("add", "authored.txt")
        os.remove(os.path.join(split.path, ".commit-attribution", "record"))
        split.git("commit", "-qm", "partial")
        open(os.path.join(split.path, ".commit-attribution", "skip-next"), "w").close()

        # The hook fires for that shell call. It must record nothing.
        fire("PostToolUse", split.path, model="gpt-5-codex")
        check(split.records() == [], "committer was recorded: %r" % split.records())

        # ...and only that one call. The next is a normal author again.
        fire("PostToolUse", split.path, model="gpt-5-codex")
        check(
            split.records() == ["Codex|gpt-5-codex"],
            "skip was not one-shot: %r" % split.records(),
        )

        # A leftover marker must not outlive a purge.
        split.git("add", "-A")
        split.git("commit", "-qm", "rest")
        open(os.path.join(split.path, ".commit-attribution", "skip-next"), "w").close()
        fire("Stop", split.path)
        check(
            not os.path.exists(
                os.path.join(split.path, ".commit-attribution", "skip-next")
            ),
            "purge left a skip marker to eat the next real record",
        )

        # --- a malformed payload must not crash the session ---
        result = subprocess.run(
            [sys.executable, HOOK], input="not json", capture_output=True, text=True
        )
        check(result.returncode == 0, "bad payload exited %s" % result.returncode)
    finally:
        shutil.rmtree(root, ignore_errors=True)

    for failure in failures:
        print("FAIL: %s" % failure, file=sys.stderr)
    if failures:
        return 1
    print("all record-attribution checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
