#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Generated By: Claude Code (Claude Opus 4.6)
#
# detect-checks.sh — validation engine for the /commit skill.
#
# Cascades through three modes and RUNS the selected validation directly,
# writing full per-job logs to .tmp-commit-skill/ and emitting a
# machine-readable summary on stdout for the skill to parse. The skill is
# not a middle-man: this script is the only thing that decides what to run
# and the only thing that runs it. The skill reads the summary, surfaces
# the log directory to the user for analysis, and routes user consent via
# AskUserQuestion where explicit acknowledgment is needed.
#
# Mode cascade (first match wins):
#   (a) act mode  — act is installed, a working DOCKER_HOST can be
#                   resolved, and `act pull_request --list` returns at
#                   least one job. Runs every listed job via act with the
#                   project's security flags. No gh / rulesets dependency —
#                   the workflow files in .github/workflows/ are the source
#                   of truth, which works on private repos without a paid
#                   plan and on repos with non-GitHub remotes too.
#   (b) make mode — Makefile exists AND declares a literal `check:` target.
#                   Runs `make check` once.
#   (c) bare mode — nothing above applied. Runs no validation; emits a
#                   REASON summarizing what was tried and a DIAGNOSTIC
#                   block with concrete fix commands for the user.
#
# Output contract on stdout: see SKILL.md "Validation (auto-detected)".
#
# Exit codes:
#   0 — dispatch completed AND validation passed (act pass, make pass, or
#       bare mode entered with user consent required).
#   1 — validation failed (any act job or `make check` failed) OR dispatch
#       cannot start (not a git repo, invoked from a subdirectory, git
#       broken). On validation failure the summary is still written so the
#       skill can parse failure details; only the exit code changes.

set -u

LOGDIR=".tmp-commit-skill"
IMG="docker.io/catthehacker/ubuntu:act-22.04@sha256:d83455c10c9a31c9c944a4c5628360c6c374983fa6616bd2439ab88b05ae2046"
LOGFILE_TAIL_LINES=30

# Populated by resolve_docker_host().
DOCKER_HOST_URI=""
DOCKER_HOST_REASON=""

# ---- Repo-root precondition --------------------------------------------------
# git rev-parse --show-prefix returns the path from repo root to cwd (empty
# string at root). Also fails cleanly when not in a git repo at all, so one
# check subsumes both the not-a-repo hard-fail and the subdirectory guard.
if ! PREFIX=$(git rev-parse --show-prefix 2>/dev/null); then
  echo "Not a git repository (cwd: $PWD)"
  exit 1
fi
if [ -n "$PREFIX" ]; then
  echo "Must be invoked from repo root. Currently ${PREFIX%/} below it. cd to the repo root and retry."
  exit 1
fi

# ---- Log dir bootstrap (pre-lock) -------------------------------------------
# Wipe and recreate BEFORE acquiring the lock so the agent sees an explicit
# "untested" state if the script blocks on flock and the bash call times out.
# Without this, the agent would read stale output from a previous run.
rm -rf "$LOGDIR"
mkdir -p "$LOGDIR"
printf '*\n' > "$LOGDIR/.gitignore"
printf 'MODE: untested\nREASON: waiting for global lock\n' > "$LOGDIR/summary.txt"

# ---- Global lock -------------------------------------------------------------
# Serializes /commit invocations across all repos. Required because act names
# containers from workflow+job only (no repo path), so concurrent runs in repos
# with identically named workflows would collide.
#
# Uses mkdir as the lock primitive — it fails atomically if the directory
# already exists, and works on every platform (Linux, macOS, Windows/MSYS2).
# A PID file inside the lock dir detects stale locks from crashed processes.
LOCKDIR="/tmp/claude-commit-skill.lock"
PIDFILE="$LOCKDIR/pid"

acquire_lock() {
  while ! mkdir "$LOCKDIR" 2>/dev/null; do
    if [ -f "$PIDFILE" ]; then
      local owner
      owner=$(cat "$PIDFILE" 2>/dev/null)
      if [ -n "$owner" ] && ! kill -0 "$owner" 2>/dev/null; then
        # Owner is dead — stale lock.
        rm -rf "$LOCKDIR"
        continue
      fi
    else
      # Lock dir exists but no PID file — owner crashed between mkdir and
      # writing the PID, or the file was removed. Either way, stale.
      rm -rf "$LOCKDIR"
      continue
    fi
    sleep 1
  done
  echo $$ > "$PIDFILE"
}

release_lock() {
  rm -rf "$LOCKDIR"
}

acquire_lock
trap release_lock EXIT

now_iso() {
  date -u '+%Y-%m-%dT%H:%M:%SZ'
}

write_summary_header() {
  {
    printf 'MODE: %s\n' "$1"
    printf 'TIMESTAMP: %s\n' "$(now_iso)"
    printf 'PWD: %s\n' "$PWD"
  } > "$LOGDIR/summary.txt"
}

emit_tail_section() {
  local logfile="$1"
  echo "--- START logfile=$logfile ---"
  tail -n $LOGFILE_TAIL_LINES "$logfile" 2>/dev/null || echo '(log file missing)'
  echo "--- END logfile=$logfile ---"
}

emit_diagnostic_block() {
  # Emits a DIAGNOSTIC block around the caller's multi-line text so the skill
  # can surface it verbatim to the user. Input comes from stdin.
  echo "--- DIAGNOSTIC ---"
  cat
  echo "--- END DIAGNOSTIC ---"
}

# ---- Docker host resolution --------------------------------------------------
# Populates DOCKER_HOST_URI on success or DOCKER_HOST_REASON on failure.
# Cascade:
#   1. Linux user socket at /run/user/$(id -u)/podman/podman.sock if present
#      as a real socket file. Works on Linux where podman.socket is active.
#   2. If a `podman machine` is running, prefer its Windows named pipe
#      (PodmanPipe.Path, populated on Windows hosts) and fall back to the
#      macOS/Linux-VM unix socket (PodmanSocket.Path).
#   3. Otherwise populate DOCKER_HOST_REASON with platform-specific fix
#      instructions and return non-zero.
#
# The current-user Linux socket check runs first on any OS — if the path is
# live, it's always the fastest route. On Windows Git Bash that path is
# phantom (the UID $(id -u) returns is a Windows RID and /run/user doesn't
# exist), so it falls through to podman machine discovery.
resolve_docker_host() {
  local uname_s sock pipe machine_state pipe_name
  uname_s=$(uname -s 2>/dev/null || echo unknown)

  # (1) Linux user socket — preferred when present.
  sock="/run/user/$(id -u 2>/dev/null || echo 0)/podman/podman.sock"
  if [ -S "$sock" ]; then
    DOCKER_HOST_URI="unix://$sock"
    return 0
  fi

  # (2) podman machine discovery.
  if ! command -v podman >/dev/null 2>&1; then
    case "$uname_s" in
      Linux)
        DOCKER_HOST_REASON="podman not found on PATH and no Linux user socket at $sock.
PLATFORM: $uname_s
TO FIX:
  1. Install podman: https://podman.io/docs/installation
  2. systemctl --user start podman.socket
  3. Verify: test -S $sock && echo ok
  4. Enable on boot: systemctl --user enable podman.socket
  5. If lingering needed: sudo loginctl enable-linger \$USER"
        ;;
      MINGW*|MSYS*|CYGWIN*)
        DOCKER_HOST_REASON="podman not found on PATH.
PLATFORM: $uname_s
TO FIX:
  1. Install Podman Desktop or podman.exe from https://podman.io
  2. podman machine init
  3. podman machine start
  4. Verify: podman run --rm hello-world"
        ;;
      *)
        DOCKER_HOST_REASON="podman not found on PATH.
PLATFORM: $uname_s
TO FIX: install podman for your platform (https://podman.io) and ensure a machine/socket is running."
        ;;
    esac
    return 1
  fi

  machine_state=$(podman machine list --format '{{.Running}}' 2>/dev/null | head -1)
  if [ "$machine_state" != "true" ]; then
    case "$uname_s" in
      Linux)
        DOCKER_HOST_REASON="No Linux user socket at $sock and no podman machine is running.
PLATFORM: $uname_s
PODMAN: $(podman --version 2>/dev/null)
TO FIX:
  1. systemctl --user start podman.socket
  2. Verify: test -S $sock && echo ok
  3. Enable on boot: systemctl --user enable podman.socket
  4. If lingering needed: sudo loginctl enable-linger \$USER"
        ;;
      MINGW*|MSYS*|CYGWIN*|Darwin)
        DOCKER_HOST_REASON="podman machine is not running.
PLATFORM: $uname_s
PODMAN: $(podman --version 2>/dev/null)
TO FIX:
  1. podman machine start
  2. Verify: podman machine list
  3. Smoke test: podman run --rm hello-world"
        ;;
      *)
        DOCKER_HOST_REASON="podman machine is not running on unknown platform $uname_s.
PODMAN: $(podman --version 2>/dev/null)
TO FIX: podman machine start (or start your podman service, depending on your setup)."
        ;;
    esac
    return 1
  fi

  # Machine is running. Prefer the Windows named pipe (PodmanPipe.Path is
  # only populated on Windows hosts — on macOS and Linux VMs it comes back
  # empty or '<no value>' depending on podman version).
  pipe=$(podman machine inspect --format '{{.ConnectionInfo.PodmanPipe.Path}}' 2>/dev/null | head -1)
  if [ -n "$pipe" ] && [ "$pipe" != "<no value>" ]; then
    # Convert \\.\pipe\podman-machine-default → npipe:////./pipe/podman-machine-default
    # Strip everything up to and including the last backslash.
    pipe_name="${pipe##*\\}"
    DOCKER_HOST_URI="npipe:////./pipe/$pipe_name"
    return 0
  fi

  # Fall back to PodmanSocket.Path (macOS and some Linux-VM setups).
  sock=$(podman machine inspect --format '{{.ConnectionInfo.PodmanSocket.Path}}' 2>/dev/null | head -1)
  if [ -n "$sock" ] && [ "$sock" != "<no value>" ] && [ -S "$sock" ]; then
    DOCKER_HOST_URI="unix://$sock"
    return 0
  fi

  DOCKER_HOST_REASON="podman machine is running but no usable connection endpoint was discovered.
PLATFORM: $uname_s
PODMAN: $(podman --version 2>/dev/null)
TRIED:
  - PodmanPipe.Path: '${pipe:-<empty>}' (Windows named pipe)
  - PodmanSocket.Path: '${sock:-<empty>}' (unix socket)
TO FIX:
  1. Restart the machine: podman machine stop && podman machine start
  2. Inspect output: podman machine inspect
  3. Update podman (PodmanPipe requires podman >= 4.4 on Windows)"
  return 1
}

# ---- Mode (a): act path probe ------------------------------------------------
# Uses `act pull_request --list` as the single source of truth for what to run.
# No gh API dependency — rulesets require a paid GitHub plan for private repos
# and the reliable answer to "what should /commit validate" is "every
# pull_request-triggered job act already knows about in this repo".
#
# Diagnostic note: act's stdout+stderr from the probe is always captured to
# $LOGDIR/probe-act-list.log BEFORE any success/failure branch, so when the
# probe rejects for any reason (non-zero exit, empty output, zero data rows)
# the user can inspect the raw output post-hoc without re-running anything.
# This is load-bearing — it's the only way to distinguish "act crashed on a
# workflow parse error" from "act ran fine but this repo has no pull_request
# jobs" from "act ran fine but returned a shape the awk filter rejects".
try_act_mode() {
  command -v act >/dev/null 2>&1 || return 1
  [ -n "$DOCKER_HOST_URI" ] || return 1

  local probe_log="$LOGDIR/probe-act-list.log"
  DOCKER_HOST=$DOCKER_HOST_URI act pull_request --list \
    -P "ubuntu-latest=$IMG" \
    --container-daemon-socket=- \
    --privileged=false \
    --insecure-secrets=false \
    > "$probe_log" 2>&1
  local rc=$?
  if [ $rc -ne 0 ]; then
    printf 'probe-exit-code: %s\n' "$rc" > "$LOGDIR/.probe-act-rc"
    return 1
  fi

  # Require at least one real data row. act --list emits:
  #   line 1: `time="..." level=info msg="Using docker host..."` (chatter)
  #   line 2: `Stage  Job ID  Job name  Workflow name  Workflow file  Events` (header)
  #   line 3+: actual job rows with numeric Stage in column 1
  # Filter on column-1 being an integer — this skips both chatter lines and
  # the header row without relying on positional line numbers.
  local job_count
  job_count=$(awk '$1 ~ /^[0-9]+$/ {n++} END {print n+0}' "$probe_log")
  if [ "$job_count" -eq 0 ]; then
    printf 'probe-exit-code: 0 (zero data rows)\n' > "$LOGDIR/.probe-act-rc"
    return 1
  fi

  cp "$probe_log" "$LOGDIR/.jobs"
  return 0
}

# Diagnostic string for why act mode did not apply — only called when act mode
# did not activate. Always points at the probe log so the user can inspect the
# raw output act actually produced.
act_reject_reason() {
  if ! command -v act >/dev/null 2>&1; then
    echo "act not installed"
    return
  fi
  if [ -z "$DOCKER_HOST_URI" ]; then
    echo "no reachable DOCKER_HOST (see DIAGNOSTIC block)"
    return
  fi
  if [ ! -d .github/workflows ]; then
    echo "no .github/workflows directory"
    return
  fi
  local probe_log="$LOGDIR/probe-act-list.log"
  local rc_note=""
  if [ -f "$LOGDIR/.probe-act-rc" ]; then
    rc_note=" ($(cat "$LOGDIR/.probe-act-rc"))"
  fi
  echo "act pull_request --list produced no runnable jobs${rc_note} — full probe output: $probe_log"
}

# ---- Mode (b): make path probe -----------------------------------------------
# Uses `make -np` to dump the fully-expanded make database, which includes
# targets defined in included Makefiles. The awk filter looks for a literal
# `check:` target declaration line.
try_make_mode() {
  [ -f Makefile ] || return 1
  make -np 2>/dev/null | awk '/^check:/ {found=1; exit} END {exit !found}'
}

make_reject_reason() {
  if [ ! -f Makefile ]; then
    echo "no Makefile"
    return
  fi
  echo "Makefile has no 'check:' target"
}

# ---- Execute: act mode -------------------------------------------------------
# Iterates every Job ID from the cached `act pull_request --list` output and
# runs it via act. Column 2 of act --list is the Job ID, which is always a
# simple identifier (matrix expansion affects Job name in column 3, not the
# ID). Buffers per-check output so RESULT can be computed across all jobs
# before the header is emitted — the skill parses RESULT from the header,
# not from trailing lines.
run_act_mode() {
  local buffer job_id logfile
  buffer="$LOGDIR/.buffer"
  : > "$buffer"

  write_summary_header act

  local any_fail=0 any_pass=0 first_job=1

  # Same column-1-numeric filter as the probe count — both must agree or
  # run_act_mode would attempt to execute jobs that the count said didn't
  # exist, or skip jobs the count included.
  while IFS= read -r job_id; do
    [ -z "$job_id" ] && continue
    logfile="$LOGDIR/act-${job_id}.log"

    # --reuse preserves container state across runs. The first job sets up the
    # container fresh; subsequent jobs reuse it to avoid redundant setup and
    # file copies.
    local reuse_flag=()
    if [ $first_job -eq 0 ]; then
      reuse_flag=(--reuse)
    fi
    first_job=0

    if DOCKER_HOST=$DOCKER_HOST_URI act pull_request \
      -P "ubuntu-latest=$IMG" \
      --container-daemon-socket=- \
      --privileged=false \
      --insecure-secrets=false \
      "${reuse_flag[@]}" \
      -j "$job_id" \
      > "$logfile" 2>&1
    then
      any_pass=1
      printf 'CHECK: %s PASS\n' "$job_id" >> "$buffer"
      printf 'CHECK: %s PASS (log: %s)\n' "$job_id" "$logfile" >> "$LOGDIR/summary.txt"
    else
      any_fail=1
      printf 'CHECK: %s FAIL\n' "$job_id" >> "$buffer"
      emit_tail_section "$logfile" >> "$buffer"
      printf 'CHECK: %s FAIL (log: %s)\n' "$job_id" "$logfile" >> "$LOGDIR/summary.txt"
    fi
  done < <(awk '$1 ~ /^[0-9]+$/ {print $2}' "$LOGDIR/.jobs")

  local result
  if [ $any_fail -eq 1 ]; then
    result=fail
  else
    result=pass
  fi

  printf 'RESULT: %s\n' "$result" >> "$LOGDIR/summary.txt"
  printf 'DOCKER_HOST: %s\n' "$DOCKER_HOST_URI" >> "$LOGDIR/summary.txt"

  printf 'MODE: act\n'
  printf 'RESULT: %s\n' "$result"
  printf 'LOGDIR: %s/\n' "$LOGDIR"
  printf 'DOCKER_HOST: %s\n' "$DOCKER_HOST_URI"
  cat "$buffer"
  rm -f "$buffer"

  [ "$result" = "pass" ]
}

# ---- Execute: make mode ------------------------------------------------------
run_make_mode() {
  local logfile="$LOGDIR/make-check.log"
  write_summary_header make
  printf 'TARGET: check\n' >> "$LOGDIR/summary.txt"

  if make check > "$logfile" 2>&1; then
    printf 'RESULT: pass (log: %s)\n' "$logfile" >> "$LOGDIR/summary.txt"
    printf 'MODE: make\n'
    printf 'TARGET: check\n'
    printf 'RESULT: pass\n'
    printf 'LOGDIR: %s/\n' "$LOGDIR"
    return 0
  fi

  printf 'RESULT: fail (log: %s)\n' "$logfile" >> "$LOGDIR/summary.txt"
  printf 'MODE: make\n'
  printf 'TARGET: check\n'
  printf 'RESULT: fail\n'
  printf 'LOGDIR: %s/\n' "$LOGDIR"
  emit_tail_section "$logfile"
  return 1
}

# ---- Execute: bare mode ------------------------------------------------------
# Bare mode carries a one-line REASON plus a multi-line DIAGNOSTIC block when
# the caller has actionable fix context (e.g., Docker resolution failed with
# specific next-step commands). The skill renders both to the user.
run_bare_mode() {
  local reason="$1"
  local diagnostic="$2"
  write_summary_header bare
  printf 'REASON: %s\n' "$reason" >> "$LOGDIR/summary.txt"
  if [ -n "$diagnostic" ]; then
    printf -- '--- DIAGNOSTIC ---\n%s\n--- END DIAGNOSTIC ---\n' "$diagnostic" >> "$LOGDIR/summary.txt"
  fi

  printf 'MODE: bare\n'
  printf 'LOGDIR: %s/\n' "$LOGDIR"
  printf 'REASON: %s\n' "$reason"
  if [ -n "$diagnostic" ]; then
    printf '%s\n' "$diagnostic" | emit_diagnostic_block
  fi
}

# ---- Dispatch ----------------------------------------------------------------
# Try act mode first. Resolving DOCKER_HOST is a prerequisite; if that fails,
# record the diagnostic and fall through to make mode. If make mode also
# doesn't apply, enter bare mode and propagate the DOCKER_HOST diagnostic so
# the user sees why act was skipped.
docker_host_diagnostic=""
if resolve_docker_host; then
  :
else
  docker_host_diagnostic="$DOCKER_HOST_REASON"
fi

if try_act_mode; then
  if run_act_mode; then
    exit 0
  fi
  exit 1
fi

act_reason=$(act_reject_reason)

if try_make_mode; then
  if run_make_mode; then
    exit 0
  fi
  exit 1
fi

make_reason=$(make_reject_reason)

bare_reason="act=${act_reason}, make=${make_reason}"
run_bare_mode "$bare_reason" "$docker_host_diagnostic"
exit 0
